version: '3.7'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - '8080:3000'
    depends_on:
      - redis
      - db
  redis:
    image: redis
    container_name: redis
    expose:
      - '6379'
    restart: always
    volumes:
      - ./docker/redis:/data
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker_password
      MYSQL_DATABASE: nasomi
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_password
